### ISSUE TITLE
mapFrom does not call its mapper

### ISSUE THREAD

**Issue by Kui-kui** [WaldoJeffers/transformer#5]
Hello WaldoJeffers 👋 

When I use `mapFrom`, the key I apply it on ends up `undefined` as if the mapper was never called. 
By the way, the last test [here](https://github.com/WaldoJeffers/transformer/blob/master/__tests__/transformers/mapFrom.js) is skipped 🙈

**Comment by WaldoJeffers** [comment]
It's actually more of a documentation issue following the release of v2.
The mapper function provided `mapFrom` will be called with a single value if a single string was passed as the first argument, or as an array if the first argument to `mapFrom` was an array.
Should be fixed by https://github.com/WaldoJeffers/transformer/commit/3bc8fad342ee1ba400bae07cafbbbe2f4f1fb45d
Can we close this?


## Valid in v2 ✅ 
```js
import { transform, mapFrom } from '@waldojeffers/transformer'

const input = { firstName: 'Waldo', lastName: 'Jeffers' }
const transformer = transform({
  fullName: mapFrom(['firstName', 'lastName'], arr => arr.join(' ')),
  firstname: mapFrom('firstName', str => str.toLowerCase())
})
```

## Invalid in v2 ❌  
```js
import { transform, mapFrom } from '@waldojeffers/transformer'

const input = { firstName: 'Waldo', lastName: 'Jeffers' }
const transformer = transform({
  fullName: mapFrom(['firstName', 'lastName'], (a, b) => a + ' ' + b),
  names: mapFrom(['firstName', 'lastName'], ({firstName, lastName}) => firstName + ' ' + lastName),
})
```
